=== Evangileon/WPL-HW3/BookPage/xml/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name="nameType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][A-Za-z]*"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="dateOfBirth">
        <xsd:restriction base="xsd:date">
            <xsd:minInclusive value="1970-01-01"/>
            <xsd:maxInclusive value="2000-12-31"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="educationType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="BA"/>
            <xsd:enumeration value="BS"/>
            <xsd:enumeration value="MS"/>
            <xsd:enumeration value="PHD"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="streetNameType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]+\s[A-Za-z0-9\s]+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="cityType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([A-Z][A-Za-z]*\s?)+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="countryType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z]+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="addressType">
        <xsd:sequence>
            <xsd:element name="StreetName" type="streetNameType" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="AptNumber" minOccurs="0" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minExclusive value="100"/>
                        <xsd:maxInclusive value="2000"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="City" type="cityType" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="ZipCode" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer"/>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="Country" type="countryType" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="numberOfPreviousBooksType">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"/>
            <xsd:maxExclusive value="100"/>
        </xsd:restriction>
    </xsd:simpleType>


    <xsd:complexType name="authorInformationType">
        <xsd:sequence>
            <xsd:element name="AuthorName" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="LastName" type="nameType" minOccurs="1" maxOccurs="1"/>
                        <xsd:element name="FirstName" type="nameType" minOccurs="1" maxOccurs="1"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="AuthorDateOfBirth" type="dateOfBirth" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="AuthorHighestEducation" type="educationType" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="AuthorAddress" type="addressType" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="NumberAuthorPreviousBooks" type="numberOfPreviousBooksType" minOccurs="1" maxOccurs="1"/>

            <xsd:element name="CoAuthorName" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="titleType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([A-Z][A-Za-z0-9]*[:\-]?\s*)+"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="isbnType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Za-z0-9]{3}-[A-Za-z0-9]{3}-[A-Za-z0-9]{4}"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="priceType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:decimal">
                <xsd:attribute name="currency">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="pound"/>
                            <xsd:enumeration value="euro"/>
                            <xsd:enumeration value="dollar"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:attribute>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="publisherInformationType">
        <xsd:sequence>
            <xsd:element name="PublisherName" type="titleType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="PublisherAddress" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="StreetName" type="streetNameType" minOccurs="1" maxOccurs="1"/>
                        <xsd:element name="SuiteNumber" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
                        <xsd:element name="City" type="cityType" minOccurs="1" maxOccurs="1"/>
                        <xsd:element name="ZipCode" type="xsd:integer"/>
                        <xsd:element name="Country" type="countryType"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="myDuration">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d\d? \d\d? \d\d?"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="bookInformationType">
        <xsd:sequence>
            <xsd:element name="Title" type="titleType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="ISBN" type="isbnType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="Price" type="priceType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="PublicationDate" type="xsd:date" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="PublisherInformation" type="publisherInformationType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="TotalTimeInCirculation" type="myDuration"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="bookType">
        <xsd:sequence>
            <xsd:element name="AuthorInformation" type="authorInformationType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="BookInformation" type="bookInformationType" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="Books">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Book" type="bookType" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Evangileon/WPL-HW3/Dummy/src/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="books.xsd">
    <Book>
        <AuthorInformation>
            <AuthorName>
                <LastName>Meyer</LastName>
                <FirstName>Stephenie</FirstName>
            </AuthorName>
            <AuthorDateOfBirth>1973-12-24</AuthorDateOfBirth>
            <AuthorHighestEducation>BS</AuthorHighestEducation>
            <AuthorAddress>
                <StreetName>814 Cave Creek Rd</StreetName>
                <City>Cave Creek</City>
                <ZipCode>75331</ZipCode>
                <Country>USA</Country>
            </AuthorAddress>
            <NumberAuthorPreviousBooks>1</NumberAuthorPreviousBooks>
        </AuthorInformation>
        <BookInformation>
            <Title>New Moon</Title>
            <ISBN>031-602-4961</ISBN>
            <Price currency="dollar">9.59</Price>
            <PublicationDate>2008-05-31</PublicationDate>
            <PublisherInformation>
                <PublisherName>Little Brown And Company</PublisherName>
                <PublisherAddress>
                    <StreetName>3 Center Plz</StreetName>
                    <City>Boston</City>
                    <ZipCode>02108</ZipCode>
                    <Country>USA</Country>
                </PublisherAddress>
            </PublisherInformation>
            <TotalTimeInCirculation>5 11 12</TotalTimeInCirculation>
        </BookInformation>
    </Book>
    
    <Book>
        <AuthorInformation>
            <AuthorName>
                <LastName>Roth</LastName>
                <FirstName>Veronica</FirstName>
            </AuthorName>
            <AuthorDateOfBirth>1988-08-19</AuthorDateOfBirth>
            <AuthorHighestEducation>BS</AuthorHighestEducation>
            <AuthorAddress>
                <StreetName>110 West 40th Street</StreetName>
                <AptNumber>410</AptNumber>
                <City>New York</City>
                <ZipCode>10018</ZipCode>
                <Country>USA</Country>
            </AuthorAddress>
            <NumberAuthorPreviousBooks>1</NumberAuthorPreviousBooks>
        </AuthorInformation>
        <BookInformation>
            <Title>Insurgent: Divergent Series</Title>
            <ISBN>006-202-4043</ISBN>
            <Price currency="dollar">9.83</Price>
            <PublicationDate>2012-05-01</PublicationDate>
            <PublisherInformation>
                <PublisherName>Katherine Tegen Books</PublisherName>
                <PublisherAddress>
                    <StreetName>1350 Avenue of the Americas</StreetName>
                    <City>New York</City>
                    <ZipCode>10019</ZipCode>
                    <Country>USA</Country>
                </PublisherAddress>
            </PublisherInformation>
            <TotalTimeInCirculation>4 5 7</TotalTimeInCirculation>
        </BookInformation>
    </Book>
    
    <Book>
        <AuthorInformation>
            <AuthorName>
                <LastName>Piketty</LastName>
                <FirstName>Thomas</FirstName>
            </AuthorName>
            <AuthorDateOfBirth>1971-05-07</AuthorDateOfBirth>
            <AuthorHighestEducation>PHD</AuthorHighestEducation>
            <AuthorAddress>
                <StreetName>48 Boulevard Jourdan</StreetName>
                <City>Paris</City>
                <ZipCode>75014</ZipCode>
                <Country>FRA</Country>
            </AuthorAddress>
            <NumberAuthorPreviousBooks>10</NumberAuthorPreviousBooks>
        </AuthorInformation>
        <BookInformation>
            <Title>Capital In The Twenty-First Century</Title>
            <ISBN>067-443-000X</ISBN>
            <Price currency="dollar">23.97</Price>
            <PublicationDate>2014-03-10</PublicationDate>
            <PublisherInformation>
                <PublisherName>Belknap Press</PublisherName>
                <PublisherAddress>
                    <StreetName>79 Garden Street</StreetName>
                    <City>Cambridge</City>
                    <ZipCode>02138</ZipCode>
                    <Country>USA</Country>
                </PublisherAddress>
            </PublisherInformation>
            <TotalTimeInCirculation>0 5 10</TotalTimeInCirculation>
        </BookInformation>
    </Book>
</Books>
